FROM zombymediaic/corebase:alpine-latest
LABEL org.opencontainers.image.maintainer="AsP3X"

WORKDIR /tmp

RUN apk update && apk add curl

RUN curl -LO https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.6%2B10/OpenJDK17U-jdk_x64_alpine-linux_hotspot_17.0.6_10.tar.gz

RUN tar xvzf OpenJDK17U-jdk_x64_alpine-linux_hotspot_17.0.6_10.tar.gz && \
    rm OpenJDK17U-jdk_x64_alpine-linux_hotspot_17.0.6_10.tar.gz

ENV JAVA_HOME /tmp/jdk-17.0.6+10
ENV PATH "$JAVA_HOME/bin:$PATH"

WORKDIR /